// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTSfp6XAiAuuJiGSVxpFAj-NczLbAIQ20',
    appId: '1:358101406987:web:9e07c48181fb1d9cc2fe0e',
    messagingSenderId: '358101406987',
    projectId: 'flutter-todo-app-64776',
    authDomain: 'flutter-todo-app-64776.firebaseapp.com',
    storageBucket: 'flutter-todo-app-64776.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa7ELWkFhS1iQxPhFX8WbIu2bQAxEEqsQ',
    appId: '1:358101406987:android:46d1fe31082774fbc2fe0e',
    messagingSenderId: '358101406987',
    projectId: 'flutter-todo-app-64776',
    storageBucket: 'flutter-todo-app-64776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCimWHl73fyPqOlMDXusqcUVSJk0vbgmEc',
    appId: '1:358101406987:ios:b74c4922d23c20b9c2fe0e',
    messagingSenderId: '358101406987',
    projectId: 'flutter-todo-app-64776',
    storageBucket: 'flutter-todo-app-64776.appspot.com',
    iosClientId: '358101406987-d06i2fhrsfjb7j8t3qmi6k72l492svve.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCimWHl73fyPqOlMDXusqcUVSJk0vbgmEc',
    appId: '1:358101406987:ios:b74c4922d23c20b9c2fe0e',
    messagingSenderId: '358101406987',
    projectId: 'flutter-todo-app-64776',
    storageBucket: 'flutter-todo-app-64776.appspot.com',
    iosClientId: '358101406987-d06i2fhrsfjb7j8t3qmi6k72l492svve.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
